[package]
name = "cv_ext_sites_jira"
version = "0.1.0"
edition = "2021"

[dependencies]
cv_ext_contract = { path = "../cv_ext_contract" }
serde.workspace = true
regex.workspace = true
serde_json.workspace = true
